version: '3'
services:
  wireguard-client:
    image: ${DOCKER_REGISTRY}monstrenyatko/wireguard-client
    container_name: wireguard-client
    restart: unless-stopped
    environment:
      - NET_LOCAL
      - WIREGUARD_PORT
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${WIREGUARD_CLIENT_CONFIG}:/etc/wireguard/wg0.conf:ro
    #ports:
    # some service web interface
    #  - 8080:8080
